service: default

runtime: java
env: flex

runtime_config:
  jdk: openjdk8
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp,mysql"
  REDISHOST: '10.161.193.139'
  REDISPORT: '6379'

handlers:
  - url: /.*
    script: this field is required, but ignored

manual_scaling:
  instances: 1

##  unix  domain socket
beta_settings:
  cloud_sql_instances: gamescore-goodjob:us-central1:gamescore

## Update with Redis instance network name
network:
  name: default

vpc_access_connector:
  name: 'projects/gamescore-goodjob/locations/us-central1/redis-vpc-connector'

resources:
  cpu: 1
  memory_gb: 2.3 #0.5
  disk_size_gb: 10
  volumes:
    - name: ramdisk1
      volume_type: tmpfs
      size_gb: 0.5


### tcp port
#beta_settings:
#  cloud_sql_instances: gamescore-goodjob:us-central1:gamescore=tcp:3307